package dev.ynagai.ondevice

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.buffer
import kotlinx.coroutines.flow.channelFlow
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import platform.Foundation.NSError
// Namespace is generated by the Kotlin/Native swiftPM cinterop from the group +
// project name; the doubled `ondevice` segment is intentional, not a typo.
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMGenerationOptions
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMLanguageModelSession
// AFMSamplingMode is a typealias for NSInteger (cinterop maps the SWIFT_ENUM to a
// Long), so the cases are imported as top-level constants, not enum entries.
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMSamplingModeNucleus
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMSamplingModeTopK
import kotlin.concurrent.Volatile
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

@OptIn(ExperimentalForeignApi::class)
actual fun createOnDeviceGenerator(): OnDeviceGenerator = IosOnDeviceGenerator()

@OptIn(ExperimentalForeignApi::class)
class IosOnDeviceGenerator : OnDeviceGenerator {

    // The device runs one generation at a time, so serialize calls. Cancellation tears
    // the in-flight generation down (see session.cancel below), freeing the lock promptly
    // rather than holding it for an abandoned generation.
    private val mutex = Mutex()

    // The session for the in-flight call, retained so the non-suspending close() can stop
    // it from off-thread. Only one call is active at a time (mutex), so a plain @Volatile
    // slot is enough; it is set at the start of a call and cleared in its finally.
    @Volatile
    private var session: AFMLanguageModelSession? = null

    // close() is terminal (matches AndroidOnDeviceGenerator): once closed, the generator
    // must not be reused. Flagged separately because close() is non-suspending and cannot
    // take the mutex.
    @Volatile
    private var closed = false

    override suspend fun generate(request: OnDeviceRequest): OnDeviceResponse =
        withSession(request, "On-device inference failed") { session ->
            val text = suspendCancellableCoroutine { cont ->
                // Coroutine cancellation has no effect on the running Foundation Models
                // generation by itself; forward it to the session so the device stops.
                cont.invokeOnCancellation { session.cancel() }
                session.respondTo(request.prompt, request.toAfmOptions()) { result, error ->
                    if (error != null) cont.resumeWithException(error.toException())
                    else cont.resume(result.orEmpty())
                }
            }
            // Foundation Models exposes no finish-reason signal (a maxTokens cutoff is a
            // silent truncation), so we always report STOP — same as the streaming path.
            OnDeviceResponse(text, OnDeviceFinishReason.STOP)
        }

    override fun generateStream(request: OnDeviceRequest): Flow<OnDeviceChunk> = channelFlow {
        withSession(request, "Streaming failed") { session ->
            // Apple Foundation Models emits cumulative snapshots, so diff against the
            // previously seen text to recover incremental deltas.
            var previous = ""
            suspendCancellableCoroutine { cont ->
                cont.invokeOnCancellation { session.cancel() }
                session.streamResponseTo(
                    request.prompt,
                    request.toAfmOptions(),
                    { cumulative ->
                        val text = cumulative.orEmpty()
                        val delta = incrementalDelta(previous, text)
                        previous = text
                        // The flow uses an unlimited buffer (see buffer() below),
                        // so trySend never drops a delta under backpressure.
                        if (delta.isNotEmpty()) trySend(OnDeviceChunk.Delta(delta))
                    },
                ) { error ->
                    if (error != null) cont.resumeWithException(error.toException())
                    else cont.resume(Unit)
                }
            }
            // Foundation Models exposes no finish-reason signal (a maxTokens cutoff
            // is a silent truncation), so we always report STOP — unlike Android.
            send(OnDeviceChunk.Done(OnDeviceFinishReason.STOP))
        }
    }.buffer(Channel.UNLIMITED)

    // Serializes the call (the device runs one generation at a time), creates a per-call
    // session published to [session] so the non-suspending close() can stop it, then tears
    // it down in finally. The closed-check is doubled on purpose: the first gates entry; the
    // second guards a close() that races the publish above — it either trips this guard or,
    // having seen the session, tears it down itself. Reuse after close() is a caller
    // lifecycle error, so the IllegalStateException propagates raw (see the OnDeviceGenerator
    // contract) and is never wrapped in OnDeviceInferenceException, reserved for the model.
    private suspend fun <T> withSession(
        request: OnDeviceRequest,
        failureMessage: String,
        block: suspend (AFMLanguageModelSession) -> T,
    ): T = mutex.withLock {
        check(!closed) { "IosOnDeviceGenerator is closed" }
        val session = AFMLanguageModelSession(request.systemInstruction).also { this.session = it }
        try {
            check(!closed) { "IosOnDeviceGenerator is closed" }
            block(session)
        } catch (e: CancellationException) {
            throw e
        } catch (e: IllegalStateException) {
            throw e
        } catch (e: Exception) {
            throw OnDeviceInferenceException(failureMessage, e)
        } finally {
            session.close()
            this.session = null
        }
    }

    override fun close() {
        closed = true
        // Idempotent by design: foundation-models-objc's close()/cancel() read-and-clear the
        // retained Task atomically under a lock, so a finally-block close() racing this one (or
        // any double close on the same session) is a safe no-op — close() only cancels the
        // in-flight Task, it frees no native resource that could be double-freed.
        session?.close()
    }
}

// AFMGenerationOptions carries the sampling controls across the @objc bridge. Its
// own sentinel defaults already encode "unset" (temperature = -1, maximumResponseTokens
// = 0, samplingMode = .default, samplingSeed = -1), so set only the fields the request
// actually specifies and leave the rest at the model default.
//
// Foundation Models threads a seed only through .topK / .nucleus sampling — there is no
// "seed the default sampling" mode, so a seed left under .default is silently dropped by
// AFMGenerationOptions.resolved(). To keep [seed] effective independently of [topK]
// (matching Android, where setSeed applies on its own), a seed-only request selects
// nucleus sampling over the full distribution (probabilityThreshold = 1.0) — a seeded,
// full-distribution sample. That is the closest seedable stand-in for default sampling,
// not a guaranteed match for the model's own default strategy (which resolved() leaves
// as sampling = nil); a seed is meaningless under greedy decoding, so full-distribution
// nucleus is the only honest place to apply it.
@OptIn(ExperimentalForeignApi::class)
private fun OnDeviceRequest.toAfmOptions(): AFMGenerationOptions =
    AFMGenerationOptions().apply {
        this@toAfmOptions.temperature?.let { temperature = it }
        this@toAfmOptions.maxOutputTokens?.let { maximumResponseTokens = it.toLong() }
        this@toAfmOptions.topK?.let {
            samplingMode = AFMSamplingModeTopK
            samplingTopK = it.toLong()
        }
        this@toAfmOptions.seed?.let {
            if (this@toAfmOptions.topK == null) {
                samplingMode = AFMSamplingModeNucleus
                samplingProbabilityThreshold = 1.0
            }
            samplingSeed = it.toLong()
        }
    }

private fun NSError.toException(): Exception =
    RuntimeException("$domain (code $code): $localizedDescription")
