package dev.ynagai.ondevice

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.buffer
import kotlinx.coroutines.flow.channelFlow
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import platform.Foundation.NSError
// Namespace is generated by the Kotlin/Native swiftPM cinterop from the group +
// project name; the doubled `ondevice` segment is intentional, not a typo.
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMLanguageModelSession
import kotlin.concurrent.Volatile
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

@OptIn(ExperimentalForeignApi::class)
actual fun createOnDeviceGenerator(): OnDeviceGenerator = IosOnDeviceGenerator()

@OptIn(ExperimentalForeignApi::class)
class IosOnDeviceGenerator : OnDeviceGenerator {

    // The device runs one generation at a time, so serialize calls. Cancellation tears
    // the in-flight generation down (see session.cancel below), freeing the lock promptly
    // rather than holding it for an abandoned generation.
    private val mutex = Mutex()

    // The session for the in-flight call, retained so the non-suspending close() can stop
    // it from off-thread. Only one call is active at a time (mutex), so a plain @Volatile
    // slot is enough; it is set at the start of a call and cleared in its finally.
    @Volatile
    private var session: AFMLanguageModelSession? = null

    // close() is terminal (matches AndroidOnDeviceGenerator): once closed, the generator
    // must not be reused. Flagged separately because close() is non-suspending and cannot
    // take the mutex.
    @Volatile
    private var closed = false

    override suspend fun generate(request: OnDeviceRequest): OnDeviceResponse = mutex.withLock {
        check(!closed) { "IosOnDeviceGenerator is closed" }
        val session = AFMLanguageModelSession(request.systemInstruction).also { this.session = it }
        try {
            val text = suspendCancellableCoroutine { cont ->
                // Coroutine cancellation has no effect on the running Foundation Models
                // generation by itself; forward it to the session so the device stops.
                cont.invokeOnCancellation { session.cancel() }
                session.respondTo(
                    request.prompt,
                    request.temperature ?: UNSET_TEMPERATURE,
                    request.maxOutputTokens ?: UNSET_MAX_TOKENS,
                ) { result, error ->
                    if (error != null) cont.resumeWithException(error.toException())
                    else cont.resume(result.orEmpty())
                }
            }
            // Foundation Models exposes no finish-reason signal (a maxTokens cutoff is a
            // silent truncation), so we always report STOP — same as the streaming path.
            OnDeviceResponse(text, OnDeviceFinishReason.STOP)
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            throw OnDeviceInferenceException("On-device inference failed", e)
        } finally {
            session.close()
            this.session = null
        }
    }

    override fun generateStream(request: OnDeviceRequest): Flow<OnDeviceChunk> = channelFlow {
        mutex.withLock {
            check(!closed) { "IosOnDeviceGenerator is closed" }
            val session = AFMLanguageModelSession(request.systemInstruction)
                .also { this@IosOnDeviceGenerator.session = it }
            try {
                // Apple Foundation Models emits cumulative snapshots, so diff against the
                // previously seen text to recover incremental deltas.
                var previous = ""
                suspendCancellableCoroutine { cont ->
                    cont.invokeOnCancellation { session.cancel() }
                    session.streamResponseTo(
                        request.prompt,
                        request.temperature ?: UNSET_TEMPERATURE,
                        request.maxOutputTokens ?: UNSET_MAX_TOKENS,
                        { cumulative ->
                            val text = cumulative.orEmpty()
                            val delta = incrementalDelta(previous, text)
                            previous = text
                            // The flow uses an unlimited buffer (see buffer() below),
                            // so trySend never drops a delta under backpressure.
                            if (delta.isNotEmpty()) trySend(OnDeviceChunk.Delta(delta))
                        },
                    ) { error ->
                        if (error != null) cont.resumeWithException(error.toException())
                        else cont.resume(Unit)
                    }
                }
                // Foundation Models exposes no finish-reason signal (a maxTokens cutoff
                // is a silent truncation), so we always report STOP — unlike Android.
                send(OnDeviceChunk.Done(OnDeviceFinishReason.STOP))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                throw OnDeviceInferenceException("Streaming failed", e)
            } finally {
                session.close()
                this@IosOnDeviceGenerator.session = null
            }
        }
    }.buffer(Channel.UNLIMITED)

    override fun close() {
        closed = true
        session?.close()
    }
}

// Sentinels for the @objc bridge, which cannot carry optional primitives: a
// negative temperature / non-positive maxTokens means "unset → model default".
private const val UNSET_TEMPERATURE: Double = -1.0
private const val UNSET_MAX_TOKENS: Int = 0

private fun NSError.toException(): Exception =
    RuntimeException("$domain (code $code): $localizedDescription")
