package dev.ynagai.ondevice

import kotlinx.cinterop.ExperimentalForeignApi
// Namespace is generated by the Kotlin/Native swiftPM cinterop from the group +
// project name; the doubled `ondevice` segment is intentional, not a typo.
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMLanguageModelSession

@OptIn(ExperimentalForeignApi::class)
actual suspend fun warmUpOnDevice() {
    // prewarm() warms the process-shared model weights; a throwaway session is
    // only a handle, so later sessions still benefit from the warmed weights.
    val session = AFMLanguageModelSession(null)
    session.prewarm()
    session.close()
}

// Foundation Models exposes no token-counting API, so callers fall back to their
// own estimate.
actual suspend fun countOnDeviceTokens(request: OnDeviceRequest): Int? = null
