package dev.ynagai.ondevice

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.CancellationException
// Namespace is generated by the Kotlin/Native swiftPM cinterop from the group +
// project name; the doubled `ondevice` segment is intentional, not a typo.
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.AFMLanguageModelSession

@OptIn(ExperimentalForeignApi::class)
actual suspend fun warmUpOnDevice() {
    // Best-effort per the common contract: safe to call when the model is unavailable.
    // Foundation Models' session constructor and prewarm() are non-throwing today, but
    // enforce the contract here (mirroring the Android bestEffort wrapper) rather than
    // relying on the upstream bridge staying non-throwing across OS / library bumps.
    try {
        // prewarm() warms the process-shared model weights; a throwaway session is
        // only a handle, so later sessions still benefit from the warmed weights.
        val session = AFMLanguageModelSession(null)
        try {
            session.prewarm()
        } finally {
            session.close()
        }
    } catch (e: CancellationException) {
        throw e
    } catch (e: Exception) {
        // Swallow: warmup is a hint, not a generation. Cancellation still propagates above.
    }
}

// Foundation Models exposes no token-counting API, so callers fall back to their
// own estimate.
actual suspend fun countOnDeviceTokens(request: OnDeviceRequest): Int? = null
