package dev.ynagai.ondevice

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.buffer
import kotlinx.coroutines.flow.channelFlow
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import platform.Foundation.NSError
// Namespace is generated by the Kotlin/Native swiftPM cinterop from the group +
// module name; the doubled `ondevice` segment is intentional, not a typo.
import swiftPMImport.dev.ynagai.ondevice.ondevice.llm.OnDeviceLlmBridge
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

@OptIn(ExperimentalForeignApi::class)
actual fun createOnDeviceGenerator(): OnDeviceGenerator = IosOnDeviceGenerator()

@OptIn(ExperimentalForeignApi::class)
class IosOnDeviceGenerator : OnDeviceGenerator {

    private val bridge = OnDeviceLlmBridge()

    // A single Foundation Models session backs the bridge, and the device runs one
    // generation at a time, so serialize calls to avoid one request clobbering
    // another's session mid-flight. Cancellation tears the in-flight generation down
    // (see bridge.cancel below), so the lock is freed promptly rather than held for an
    // abandoned generation.
    private val mutex = Mutex()

    override suspend fun generate(request: OnDeviceRequest): String = mutex.withLock {
        try {
            bridge.createSession(request.systemInstruction)
            suspendCancellableCoroutine { cont ->
                // Coroutine cancellation has no effect on the running Foundation Models
                // generation by itself; forward it to the bridge so the device stops.
                cont.invokeOnCancellation { bridge.cancel() }
                bridge.generate(
                    request.prompt,
                    request.temperature ?: UNSET_TEMPERATURE,
                    request.maxOutputTokens ?: UNSET_MAX_TOKENS,
                ) { result, error ->
                    if (error != null) cont.resumeWithException(error.toException())
                    else cont.resume(result.orEmpty())
                }
            }
        } catch (e: CancellationException) {
            throw e
        } catch (e: Exception) {
            throw OnDeviceException("On-device inference failed", e)
        }
    }

    override fun generateStream(request: OnDeviceRequest): Flow<OnDeviceChunk> = channelFlow {
        mutex.withLock {
            try {
                bridge.createSession(request.systemInstruction)

                // Apple Foundation Models emits cumulative snapshots, so diff against the
                // previously seen text to recover incremental deltas.
                var previous = ""
                suspendCancellableCoroutine { cont ->
                    cont.invokeOnCancellation { bridge.cancel() }
                    bridge.streamGenerate(
                        request.prompt,
                        request.temperature ?: UNSET_TEMPERATURE,
                        request.maxOutputTokens ?: UNSET_MAX_TOKENS,
                        { cumulative ->
                            val text = cumulative.orEmpty()
                            val delta = incrementalDelta(previous, text)
                            previous = text
                            // The flow uses an unlimited buffer (see buffer() below),
                            // so trySend never drops a delta under backpressure.
                            if (delta.isNotEmpty()) trySend(OnDeviceChunk.Delta(delta))
                        },
                    ) { error ->
                        if (error != null) cont.resumeWithException(error.toException())
                        else cont.resume(Unit)
                    }
                }
                // Foundation Models exposes no finish-reason signal (a maxTokens cutoff
                // is a silent truncation), so we always report STOP — unlike Android.
                send(OnDeviceChunk.Done(OnDeviceFinishReason.STOP))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                throw OnDeviceException("Streaming failed", e)
            }
        }
    }.buffer(Channel.UNLIMITED)

    override fun close() = bridge.close()
}

// Sentinels for the @objc bridge, which cannot carry optional primitives: a
// negative temperature / non-positive maxTokens means "unset → model default".
private const val UNSET_TEMPERATURE: Double = -1.0
private const val UNSET_MAX_TOKENS: Int = 0

private fun NSError.toException(): Exception =
    RuntimeException("$domain (code $code): $localizedDescription")
